//
//  CreateOrderModels.swift
//  Clean Store
//
//  Created by Артур Азаров on 16.03.2018.
//  Copyright (c) 2018 Артур Азаров. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CreateOrder
{
    // MARK: Use cases
    
    enum FormatExpirationDate {
        struct Request {
            var date: Date
        }
        struct Response {
            var date: Date
        }
        
        struct ViewModel {
            var date: String
        }
    }
}
